---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: kube-system
  labels:
    app: myapp
  annotations:
    flux.weave.works/automated: "false"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: xiangxinyong/nginxtest:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: kube-system
  labels:
    app: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - name: http
    port: 80
    targetPort: 80
